model:
  _target_: quadra.models.classification.TimmNetworkBuilder
  model_name: resnet18.tv_in1k # Use torchvision weights
  pretrained: true
  freeze: false
metadata:
  input_size: 224
  output_dim: 512
