dataset:
  task: segmentation

model:
  input_size: [224, 224]
  backbone: resnet18.tv_in1k
  gamma_c: 1
  gamma_d: 1
  num_nearest_neighbors: 3
  num_hard_negative_features: 3
  radius: 1e-5
  lr: 1e-3
  weight_decay: 5e-4
  amsgrad: true

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive # options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

# PL Trainer Args. Don't add extra parameter here.
trainer:
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  devices: [0]
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  max_epochs: 30
  val_check_interval: 1.0 # Don't validate before extracting features.
