dataset:
  task: segmentation
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: csflow
  clamp: 3
  input_size: [256, 256] # 768 is the dimensions used in the official implementation
  cross_conv_hidden_channels: 1024
  eps: 1e-04 # Adam epsilon
  layers:
    - 6.8
  lr: 2e-4
  n_coupling_blocks: 4
  n_scales: 3
  weight_decay: 1e-5 # Adam weight decay

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: gpu # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  benchmark: false
  check_val_every_n_epoch: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: [0]
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gradient_clip_val: 1 # Grad clip value set based on the official implementation
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 240
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  num_nodes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  use_distributed_sampler: true
  sync_batchnorm: false
  val_check_interval: 1.0
