# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - core: default
  - loss: null
  - optimizer: null
  - scheduler: null
  - task: default
  - transforms: default
  - trainer: lightning_gpu
  - backbone: null
  - model: null
  - datamodule: null
  - callbacks: default
  - logger: mlflow
  - export: default
  - inference: default
  - hparams_search: null
  - hydra: default
  # BE CAREFUL TO KEEP EXPERIMENT LAST
  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

work_dir: ${hydra:runtime.cwd}
debug: False
print_config: true
ignore_warnings: true
validate: true
