defaults:
  - default_resize
  - _self_

flip_and_jitter:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.HorizontalFlip
      p: 0.5
    - _target_: albumentations.ColorJitter
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.1
      p: 0.8
    - _target_: albumentations.ToGray
      p: 0.2

augmentation1:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.RandomResizedCrop
      height: ${transforms.input_height}
      width: ${transforms.input_width}
      scale: [0.08, 1.0]
    - ${transforms.flip_and_jitter}
    - _target_: albumentations.GaussianBlur
      blur_limit: 23
      sigma_limit: [0.1, 2]
      p: 1.0
    - ${transforms.normalize}

augmentation2:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.RandomResizedCrop
      height: ${transforms.input_height}
      width: ${transforms.input_width}
      scale: [0.08, 1.0]
    - ${transforms.flip_and_jitter}
    - _target_: albumentations.GaussianBlur
      blur_limit: 23
      sigma_limit: [0.1, 2]
      p: 0.1
    - _target_: albumentations.Solarize
      p: 0.2
    - ${transforms.normalize}
