projection_mlp:
  _target_: quadra.modules.ssl.common.BYOLProjectionHead
  input_dim: ${backbone.metadata.output_dim}
  output_dim: 256
  hidden_dim: 4096

prediction_mlp:
  _target_: quadra.modules.ssl.common.BYOLPredictionHead
  input_dim: ${model.projection_mlp.output_dim}
  output_dim: ${model.projection_mlp.output_dim}
  hidden_dim: ${model.projection_mlp.hidden_dim}

student: ${backbone.model}

module:
  _target_: quadra.modules.ssl.BYOL
  classifier: ${model.classifier}
  criterion: ${loss}
  teacher_momentum: 0.9996
  lr_scheduler_interval: step

classifier:
  _target_: sklearn.neighbors.KNeighborsClassifier
  n_neighbors: 20
  n_jobs: 5
