model: ${backbone.model}

pre_classifier: null
classifier:
  _target_: torch.nn.Linear
  in_features: ${backbone.metadata.output_dim}
module:
  _target_: quadra.modules.classification.ClassificationModule
  lr_scheduler_interval: "epoch"
  criterion: ${loss}
