student_projection_mlp:
  _target_: quadra.modules.ssl.common.DinoProjectionHead
  input_dim: ${backbone.metadata.output_dim}
  output_dim: 1024
  hidden_dim: 256
  bottleneck_dim: 128
  num_layers: 3
  norm_last_layer: True

student: ${backbone.model}

teacher_projection_mlp: ${model.student_projection_mlp}

teacher: ${model.student}

module:
  _target_: quadra.modules.ssl.Dino
  classifier: ${model.classifier}
  criterion: ${loss}
  teacher_momentum: 0.996
  lr_scheduler_interval: step

classifier:
  _target_: sklearn.neighbors.KNeighborsClassifier
  n_neighbors: 20
  n_jobs: 5
