_target_: quadra.tasks.Classification
lr_multiplier: null
output:
  example: false
report: false
run_test: true
export_config:
  types: [pytorch, torchscript]
  input_shapes: # Redefine the input shape if not automatically inferred
