_target_: quadra.tasks.SklearnClassification
device: cuda:0
half_precision: false
gradcam: false
automatic_batch_size:
  starting_batch_size: 1024
  disable: true
save_model_summary: false
output:
  folder: classification_experiment
  report: true
  example: true
  test_full_data: true
