_target_: quadra.tasks.SklearnClassification
device: "cuda:0"
export_type: [torchscript]
output:
  folder: "classification_experiment"
  save_backbone: false
  report: true
  example: true
  test_full_data: true
