_target_: quadra.tasks.PatchSklearnClassification
device: cuda:2
output:
  folder: classification_patch_experiment
  save_backbone: false
  report: true
  example: true
  reconstruction_method: major_voting
