_target_: quadra.tasks.PatchSklearnClassification
device: cuda:0
half_precision: false
automatic_batch_size:
  starting_batch_size: 1024
  disable: true
output:
  folder: classification_patch_experiment
  report: true
  example: true
  reconstruction_method: major_voting
