_target_: quadra.tasks.SklearnClassification
device: "cuda:0"
output:
  folder: "classification_experiment"
  save_backbone: false
  report: true
  example: true
  test_full_data: true
export_config:
  types: [pytorch, torchscript]
  input_shapes: # Redefine the input shape if not automatically inferred
