name: Bug Report
description: File a bug report to help us improve
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version are you seeing the problem on?
      description: select all version where you have experienced this issue
      multiple: true
      options:
        - master (Default)
        - 1.0.*
    validations:
      required: true
  - type: markdown
    attributes:
      value: "**Note: The rest of this form is optional, but filling it out may help us to provide better support.**"
  - type: textarea
    attributes:
      label: How to reproduce the bug?
      description: Please provide a step-by-step description of how to reproduce this bug.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell