_target_: quadra.tasks.anomaly.AnomalibDetection
report: true
run_test: true
module_function:
  _target_: anomalib.models.patchcore.lightning_model.PatchcoreLightning
export_config:
  types: [torchscript]
  input_shapes: # Redefine the input shape if not automatically inferred

