tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "tensorboard/"
  name: ${core.name}
  version: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
