onnx:
  session_options:
    inter_op_num_threads: 8
    intra_op_num_threads: 8
    graph_optimization_level:
      _target_: onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
    enable_mem_pattern: true
    enable_cpu_mem_arena: true
    enable_profiling: false
    enable_mem_reuse: true
    execution_mode:
      _target_: onnxruntime.ExecutionMode.ORT_SEQUENTIAL
    execution_order:
      _target_: onnxruntime.ExecutionOrder.DEFAULT
    log_severity_level: 2
    log_verbosity_level: 0
    logid: ""
    optimized_model_filepath: ""
    use_deterministic_compute: false
    profile_file_prefix: onnxruntime_profile_

torch:
torchscript:
