_target_: quadra.datamodules.SegmentationDataModule
data_path: ???
test_size: 0.3
val_size: 0.3
seed: ${core.seed}
batch_size: 32
num_workers: 6
train_transform: ${transforms.train_transform}
test_transform: ${transforms.test_transform}
val_transform: ${transforms.val_transform}
train_split_file:
test_split_file:
val_split_file:
num_data_class:
exclude_good: false
enable_hashing: true
hash_size: 64
hash_type: content
