name: Build and Deploy Documentation

on:
  push:
    branches:
      # - main
      # - dev
      - feature/documentation_actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[docs]" --no-cache-dir

      - name: Build Documentation
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin gh-pages --depth=1
          VERSION="test"
          mike deploy --push $VERSION
